{
  imports = [
    ./asus.nix
    ./binutils.nix
    ./cargo.nix
    ./clippy.nix
    ./deepseek-harness.nix
    ./dotnet.nix
    ./fcitx5.nix
    ./fhs.nix
    ./firefox.nix
    ./flatpak.nix
    ./gcc.nix
    ./git.nix
    ./gnupg.nix
    ./gnumake.nix
    ./java.nix
    ./kitty.nix
    ./mtr.nix
    ./nix-ld.nix
    ./nixfmt.nix
    ./noctalia.nix
    ./noctalia-greeter.nix
    ./openssl.nix
    ./pkg-config.nix
    ./python.nix
    ./rust.nix
    ./steam.nix
    ./throne.nix
    ./umbriel.nix
    ./vim.nix
    ./vscode.nix
    ./wget.nix
    ./zsh.nix
  ];
}
